name: Deploy to cPanel

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Or your required PHP version
          extensions: pdo, mysql, mbstring, xml, ctype, json

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Copy files to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          remote_path: /home/${{ secrets.CPANEL_USERNAME }}/your-subdomain.com # Adjust the path
          source: .

      - name: Run migrations and seeders
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          script: |
            cd /home/${{ secrets.CPANEL_USERNAME }}/your-subdomain.com
            php artisan migrate --force
            php artisan db:seed --force
            php artisan optimize:clear
