- name: Deploy with Guaranteed rsync
        run: |
          # Create a wrapper script
          cat << 'EOF' > deploy.sh
          #!/bin/bash
          set -e

          # 1. Force install rsync with a clean environment
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get clean -y
          sudo apt-get update -y
          sudo apt-get install -y --reinstall rsync

          # 2. Verify installation and PATH
          if ! which rsync > /dev/null; then
            echo "::error::rsync is missing after installation"
            exit 1
          fi

          export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          echo "Current PATH: $PATH"
          which rsync
          /usr/bin/rsync --version

          # 3. Debugging directory listing
          echo "Listing /usr/bin:"
          ls -l /usr/bin | grep rsync

          # 4. Execute rsync using the full path
          echo "Deploying with rsync..."
          /usr/bin/rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/bvc_id_rsa" \
            --exclude=.git \
            --exclude=.github \
            deployment/ ${{ secrets.CPANEL_USERNAME }}@${{ env.DEPLOYMENT_PATH }}:${{ env.DEPLOYMENT_PATH }}/
          EOF

          chmod +x deploy.sh
          ./deploy.sh
